name: photo_sync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.2
  exif: ^3.3.0
  exif_reader: ^4.1.0
  ffi: ^2.2.0
  ffmpeg_kit_flutter: ^6.0.3
  ffmpeg_kit_flutter_new: ^4.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_map: ^8.3.0
  flutter_riverpod: ^3.3.1
  http: ^1.6.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pool: ^1.5.2
  random_access_source: ^4.2.1
  win32: ^6.0.1
  flutter_video_thumbnail_plus: ^1.0.6
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
